[tool.poetry]
name = "all-stock-no-fish"
version = "0.1.0"
description = "Chess analysis portfolio project"
authors = ["Louis Auger <louis.auger.pro@gmail.com>"]
packages = [{ include = "all_stock_no_fish", from = "src" }]

[tool.poetry.dependencies]
python    = "^3.12.9"
requests  = "^2.31"

[tool.poetry.group.frontend.dependencies]
streamlit = "^1.35"

[tool.poetry.group.backend.dependencies]
fastapi   = "^0.111.0"
uvicorn   = "^0.29.0"
google-cloud-bigquery = "^3.41.0"


[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
